In [1]:
import pandas as pd

In [2]:
data = {
    'Book Title': ['The Great Gatsby', 'To Kill a Mockingbird', '1984', 'Pride and Prejudice', 'The Catcher in the Rye'],
    'Author': ['F. Scott Fitzgerald', 'Harper Lee', 'George Orwell', 'Jane Austen', 'J.D. Salinger'],
    'Genre': ['Classic', 'Classic', 'Dystopian', 'Classic', 'Classic'],
    'Price': [10.99, 8.99, 7.99, 11.99, 9.99],
    'Copies Sold': [500, 600, 800, 300, 450]
}
df = pd.DataFrame(data)

In [3]:
df.head()

               Book Title               Author      Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450

In [4]:
df.describe()

           Price  Copies Sold
count   5.000000     5.000000
mean    9.990000   530.000000
std     1.581139   185.741756
min     7.990000   300.000000
25%     8.990000   450.000000
50%     9.990000   500.000000
75%    10.990000   600.000000
max    11.990000   800.000000

In [6]:
df.groupby('Price')

In [11]:
df.sort_values(by='Price' , ascending=False)

               Book Title               Author      Genre  Price  Copies Sold
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800

In [12]:
df[df['Author']=='Harper Lee']

              Book Title      Author    Genre  Price  Copies Sold
1  To Kill a Mockingbird  Harper Lee  Classic   8.99          600

In [15]:
df[df['Price']<100]

               Book Title               Author      Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('C:\\Users\\LENOVO\\Desktop\\DI-BOOTCAMP\\students.csv')
df

,id,first_name,last_name,email,date_of_birth,grade,major,enrollment_year,status
0,1,Alice,Smith,alice.smith1@example.edu,2000-01-15,92,Biology,2016,graduated
1,2,Benjamin,Lee,benjamin.lee2@example.edu,1999-03-22,88,Computer Science,2016,graduated
2,3,Chloe,Johnson,chloe.johnson3@example.edu,2001-05-08,95,Mathematics,2016,graduated
3,4,Daniel,Martinez,daniel.martinez4@example.edu,2000-07-19,84,Engineering,2016,graduated
4,5,Emma,Brown,emma.brown5@example.edu,2002-09-02,91,Psychology,2016,graduated
...,...,...,...,...,...,...,...,...,...
94,95,Grace,Wilson,grace.wilson95@example.edu,2001-02-14,93,Literature,2024,active
95,96,Henry,Taylor,henry.taylor96@example.edu,1999-04-30,86,Physics,2024,active
96,97,Isla,Anderson,isla.anderson97@example.edu,2002-06-11,90,Chemistry,2024,active
97,98,Jack,Thomas,jack.thomas98@example.edu,2001-08-23,87,History,2024,active
98,99,Kara,White,kara.white99@example.edu,2000-10-05,94,Art,2024,active

In [5]:
df.head()

,id,first_name,last_name,email,date_of_birth,grade,major,enrollment_year,status
0,1,Alice,Smith,alice.smith1@example.edu,2000-01-15,92,Biology,2016,graduated
1,2,Benjamin,Lee,benjamin.lee2@example.edu,1999-03-22,88,Computer Science,2016,graduated
2,3,Chloe,Johnson,chloe.johnson3@example.edu,2001-05-08,95,Mathematics,2016,graduated
3,4,Daniel,Martinez,daniel.martinez4@example.edu,2000-07-19,84,Engineering,2016,graduated
4,5,Emma,Brown,emma.brown5@example.edu,2002-09-02,91,Psychology,2016,graduated

In [6]:
df.tail(200)

,id,first_name,last_name,email,date_of_birth,grade,major,enrollment_year,status
0,1,Alice,Smith,alice.smith1@example.edu,2000-01-15,92,Biology,2016,graduated
1,2,Benjamin,Lee,benjamin.lee2@example.edu,1999-03-22,88,Computer Science,2016,graduated
2,3,Chloe,Johnson,chloe.johnson3@example.edu,2001-05-08,95,Mathematics,2016,graduated
3,4,Daniel,Martinez,daniel.martinez4@example.edu,2000-07-19,84,Engineering,2016,graduated
4,5,Emma,Brown,emma.brown5@example.edu,2002-09-02,91,Psychology,2016,graduated
...,...,...,...,...,...,...,...,...,...
94,95,Grace,Wilson,grace.wilson95@example.edu,2001-02-14,93,Literature,2024,active
95,96,Henry,Taylor,henry.taylor96@example.edu,1999-04-30,86,Physics,2024,active
96,97,Isla,Anderson,isla.anderson97@example.edu,2002-06-11,90,Chemistry,2024,active
97,98,Jack,Thomas,jack.thomas98@example.edu,2001-08-23,87,History,2024,active
98,99,Kara,White,kara.white99@example.edu,2000-10-05,94,Art,2024,active

In [7]:
df.shape

(99, 9)

In [8]:
df.dtypes

id                 int64
first_name           str
last_name            str
email                str
date_of_birth        str
grade              int64
major                str
enrollment_year    int64
status               str
dtype: object

In [14]:
df.columns

Index(['id', 'first_name', 'last_name', 'email', 'date_of_birth', 'grade',
       'major', 'enrollment_year', 'status'],
      dtype='str')

In [17]:
df[['grade','email']]

    grade                         email
0      92      alice.smith1@example.edu
1      88     benjamin.lee2@example.edu
2      95    chloe.johnson3@example.edu
3      84  daniel.martinez4@example.edu
4      91       emma.brown5@example.edu
..    ...                           ...
94     93    grace.wilson95@example.edu
95     86    henry.taylor96@example.edu
96     90   isla.anderson97@example.edu
97     87     jack.thomas98@example.edu
98     94      kara.white99@example.edu

[99 rows x 2 columns]

In [19]:
df ['grade']=0
df

,id,first_name,last_name,email,date_of_birth,grade,major,enrollment_year,status
0,1,Alice,Smith,alice.smith1@example.edu,2000-01-15,0,Biology,2016,graduated
1,2,Benjamin,Lee,benjamin.lee2@example.edu,1999-03-22,0,Computer Science,2016,graduated
2,3,Chloe,Johnson,chloe.johnson3@example.edu,2001-05-08,0,Mathematics,2016,graduated
3,4,Daniel,Martinez,daniel.martinez4@example.edu,2000-07-19,0,Engineering,2016,graduated
4,5,Emma,Brown,emma.brown5@example.edu,2002-09-02,0,Psychology,2016,graduated
...,...,...,...,...,...,...,...,...,...
94,95,Grace,Wilson,grace.wilson95@example.edu,2001-02-14,0,Literature,2024,active
95,96,Henry,Taylor,henry.taylor96@example.edu,1999-04-30,0,Physics,2024,active
96,97,Isla,Anderson,isla.anderson97@example.edu,2002-06-11,0,Chemistry,2024,active
97,98,Jack,Thomas,jack.thomas98@example.edu,2001-08-23,0,History,2024,active
98,99,Kara,White,kara.white99@example.edu,2000-10-05,0,Art,2024,active

In [21]:
df['test'] = 'test'
df['test']

0     test
1     test
2     test
3     test
4     test
      ...
94    test
95    test
96    test
97    test
98    test
Name: test, Length: 99, dtype: str

In [24]:
df.drop(columns=['test'])

,id,first_name,last_name,email,date_of_birth,grade,major,enrollment_year,status
0,1,Alice,Smith,alice.smith1@example.edu,2000-01-15,0,Biology,2016,graduated
1,2,Benjamin,Lee,benjamin.lee2@example.edu,1999-03-22,0,Computer Science,2016,graduated
2,3,Chloe,Johnson,chloe.johnson3@example.edu,2001-05-08,0,Mathematics,2016,graduated
3,4,Daniel,Martinez,daniel.martinez4@example.edu,2000-07-19,0,Engineering,2016,graduated
4,5,Emma,Brown,emma.brown5@example.edu,2002-09-02,0,Psychology,2016,graduated
...,...,...,...,...,...,...,...,...,...
94,95,Grace,Wilson,grace.wilson95@example.edu,2001-02-14,0,Literature,2024,active
95,96,Henry,Taylor,henry.taylor96@example.edu,1999-04-30,0,Physics,2024,active
96,97,Isla,Anderson,isla.anderson97@example.edu,2002-06-11,0,Chemistry,2024,active
97,98,Jack,Thomas,jack.thomas98@example.edu,2001-08-23,0,History,2024,active
98,99,Kara,White,kara.white99@example.edu,2000-10-05,0,Art,2024,active

In [25]:
df.rename(columns={'major':'jorant'})

,id,first_name,last_name,email,date_of_birth,grade,jorant,enrollment_year,status,test
0,1,Alice,Smith,alice.smith1@example.edu,2000-01-15,0,Biology,2016,graduated,test
1,2,Benjamin,Lee,benjamin.lee2@example.edu,1999-03-22,0,Computer Science,2016,graduated,test
2,3,Chloe,Johnson,chloe.johnson3@example.edu,2001-05-08,0,Mathematics,2016,graduated,test
3,4,Daniel,Martinez,daniel.martinez4@example.edu,2000-07-19,0,Engineering,2016,graduated,test
4,5,Emma,Brown,emma.brown5@example.edu,2002-09-02,0,Psychology,2016,graduated,test
...,...,...,...,...,...,...,...,...,...,...
94,95,Grace,Wilson,grace.wilson95@example.edu,2001-02-14,0,Literature,2024,active,test
95,96,Henry,Taylor,henry.taylor96@example.edu,1999-04-30,0,Physics,2024,active,test
96,97,Isla,Anderson,isla.anderson97@example.edu,2002-06-11,0,Chemistry,2024,active,test
97,98,Jack,Thomas,jack.thomas98@example.edu,2001-08-23,0,History,2024,active,test
98,99,Kara,White,kara.white99@example.edu,2000-10-05,0,Art,2024,active,test

In [26]:
df['grade'].astype(float)

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ...
94    0.0
95    0.0
96    0.0
97    0.0
98    0.0
Name: grade, Length: 99, dtype: float64

In [27]:
df.sort_values('date_of_birth' , ascending=True)

,id,first_name,last_name,email,date_of_birth,grade,major,enrollment_year,status,test
49,50,Felix,Davis,felix.davis50@example.edu,1998-11-27,0,Economics,2020,active,test
38,39,Felix,Davis,felix.davis39@example.edu,1998-11-27,0,Economics,2019,active,test
27,28,Felix,Davis,felix.davis28@example.edu,1998-11-27,0,Economics,2018,active,test
60,61,Felix,Davis,felix.davis61@example.edu,1998-11-27,0,Economics,2021,active,test
71,72,Felix,Davis,felix.davis72@example.edu,1998-11-27,0,Economics,2022,active,test
...,...,...,...,...,...,...,...,...,...,...
92,93,Emma,Brown,emma.brown93@example.edu,2002-09-02,0,Psychology,2024,active,test
37,38,Emma,Brown,emma.brown38@example.edu,2002-09-02,0,Psychology,2019,active,test
59,60,Emma,Brown,emma.brown60@example.edu,2002-09-02,0,Psychology,2021,active,test
26,27,Emma,Brown,emma.brown27@example.edu,2002-09-02,0,Psychology,2018,active,test
48,49,Emma,Brown,emma.brown49@example.edu,2002-09-02,0,Psychology,2020,active,test

In [30]:
df.iloc[0:5,2]

0       Smith
1         Lee
2     Johnson
3    Martinez
4       Brown
Name: last_name, dtype: str

In [17]:
df.groupby('Author')['Copies Sold'].sum()

Author
F. Scott Fitzgerald    500
George Orwell          800
Harper Lee             600
J.D. Salinger          450
Jane Austen            300
Name: Copies Sold, dtype: int64

In [18]:
# Calcul de la factorielle avec une fonction récursive
def factorielle(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorielle(n - 1)

# Exemple d'utilisation
nombre = 5
print(f"La factorielle de {nombre} est {factorielle(nombre)}")

La factorielle de 5 est 120

In [20]:
Q1 = df['Age'].quantile(0.25)

KeyError: 'Age'