In [1]:
import pandas as pd

In [2]:
data = {
    'Book Title': ['The Great Gatsby', 'To Kill a Mockingbird', '1984', 'Pride and Prejudice', 'The Catcher in the Rye'],
    'Author': ['F. Scott Fitzgerald', 'Harper Lee', 'George Orwell', 'Jane Austen', 'J.D. Salinger'],
    'Genre': ['Classic', 'Classic', 'Dystopian', 'Classic', 'Classic'],
    'Price': [10.99, 8.99, 7.99, 11.99, 9.99],
    'Copies Sold': [500, 600, 800, 300, 450]
}
df = pd.DataFrame(data)

In [3]:
df.head()

               Book Title               Author      Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450

In [4]:
df.describe()

           Price  Copies Sold
count   5.000000     5.000000
mean    9.990000   530.000000
std     1.581139   185.741756
min     7.990000   300.000000
25%     8.990000   450.000000
50%     9.990000   500.000000
75%    10.990000   600.000000
max    11.990000   800.000000

In [6]:
df.groupby('Price')

In [11]:
df.sort_values(by='Price' , ascending=False)

               Book Title               Author      Genre  Price  Copies Sold
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800

In [12]:
df[df['Author']=='Harper Lee']

              Book Title      Author    Genre  Price  Copies Sold
1  To Kill a Mockingbird  Harper Lee  Classic   8.99          600

In [15]:
df[df['Price']<100]

               Book Title               Author      Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450

In [17]:
df.groupby('Author')['Copies Sold'].sum()

Author
F. Scott Fitzgerald    500
George Orwell          800
Harper Lee             600
J.D. Salinger          450
Jane Austen            300
Name: Copies Sold, dtype: int64

In [18]:
# Calcul de la factorielle avec une fonction récursive
def factorielle(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorielle(n - 1)

# Exemple d'utilisation
nombre = 5
print(f"La factorielle de {nombre} est {factorielle(nombre)}")

La factorielle de 5 est 120

In [20]:
Q1 = df['Age'].quantile(0.25)

KeyError: 'Age'